<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="styles.css">
    <title>Presupuesto construccion</title>
</head>
<body>
<header>
    <div class="navbar">
    <?php if ($this->user): ?>
        <div class="navbar-logo">
            <a class="navbar-brand" href="listar">Presupuestos</a>
        </div>
        <div class="navbar-logo">
            <a class="navbar-brand" href="añadirPresupuesto">Armar presupuesto</a>
        </div>
        <div class="navbar-logo">
            <a class="navbar-brand" href="">Nosotros</a>
        </div>
        <div class="navbar-logo">
            <a class="navbar-brand" href="Logout">Cerrar sesión</a>
        </div>
    <?php endif; ?>
            <!-- Icono de menú desplegable -->
    <div class="navbar-toggler" id="navbar-toggler">
        <span class="bar"></span>
        <span class="bar"></span>
        <span class="bar"></span>
    </div>
</div>
<!-- Menú desplegable -->
<div class="navbar-nav" id="navbar-nav">
    <a href="listar">Presupuestos</a>
    <a href="añadirPresupuesto">Armar presupuesto</a>
    <a href="">Nosotros</a>
    <a href="Logout">Cerrar sesión</a>
    </div>
</header>
    <script src="/script.js"></script>
</body>
</html>